---

apiVersion: v1                                                            
kind: Pod                                                                 
metadata:                                                                 
  name: app-multicontainers                                              
spec:                                                                     
  containers:                                                             
  - name: container-1                                                     
    image: nginx:latest
    volumeMounts:                                                         
    - mountPath: /usr/share/nginx/html                                    
      name: html                                                       
    ports:                                                                
    - containerPort: 80                                                   
  - name: container-2                                                     
    image: alpine:latest                                                  
    command: ["sh", "-c", "while true; do echo hello; sleep 10; done"]    
  volumes:                                                                
  - name: html                                                            
    emptyDir: {}                                                          


