---

apiVersion: v1                                                            
kind: Pod                                                                 
metadata:                                                                 
  name: app-secret-env                                                           
spec:                                                                     
  containers:                                                             
    - name: app                                                  
      image: my-app                                                     
      env:                                                                
        - name: USER                                                      
          valueFrom:                                                      
            secretKeyRef:                                                 
              name: my-secret                                             
              key: user                                                   
        - name: PASSWORD                                                  
          valueFrom:                                                      
            secretKeyRef:                                                 
              name: my-secret                                             
              key: password                                               
  restartPolicy: Never                
