--- 

apiVersion: v1                                                            
kind: Pod                                                                 
metadata:                                                                 
  name: app-readinessprobe                                                          
  namespace: demo                                                 
  labels:                                                                 
    app: demo-lp                                                         
spec:                                                                     
  containers:                                                             
    - name: app                                                    
      image: us-central1-docker.pkg.dev/robotic-weft-462808-a2/k8s-learn/demo:v2.0.0                                                       
      ports:                                                                
        - containerPort: 8080
        name: http                                               
      livenessProbe:                                                        
        httpGet:                                                            
          path: /health                                                     
          port: 8080                                                        
        initialDelaySeconds: 30                                             
        timeoutSeconds: 5                                                   
        failureThreshold: 3
        periodSeconds: 10
      readinessProbe:                                                     
        httpGet:                                                          
          path: /ready                                                    
          port: 8080                                                        
        initialDelaySeconds: 5                                            
        timeoutSeconds: 5                                                 
        periodSeconds: 5
        failureThreshold: 3
        successThreshold: 1 
                             
