--- 

apiVersion: batch/v1                                                      
kind: CronJob                                                             
metadata:                                                                 
  name: app-cronjob                                                   
spec:                                                                     
  schedule: "*/5 * * * *"  # Every 5 minutes                              
  jobTemplate:                                                            
    spec:                                                                 
      template:                                                           
        spec:                                                             
          containers:                                                     
            - name: demo-cronjob                                       
              image: bash
              command: ["bash", "-c", "echo Hello from CronJob "]                                                  
          restartPolicy: OnFailure 
